version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
    groups:
      yarn-dependencies:
        patterns:
          - "yarn.lock"
        update-types:
          - patch
          - minor
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: monthly
    groups:
      actions-dependencies:
        update-types:
          - patch
          - minor
